### ISSUE TITLE
Request for fast SQRT library on RISC-V using `fsqrt.s`

### ISSUE THREAD

**Issue by jimaobian** [riscv/riscv-newlib#40]
For reference in glibc:
https://github.com/riscv/riscv-glibc/blob/4e2943456e690d89f48e6e710757dd09404b0c9a/sysdeps/riscv/rvf/e_sqrtf.c

**Comment by aswaterman** [comment]
This makes sense to reduce code size, but does it actually matter for performance in practice?  It looks like gcc already inlines the fsqrt.s instruction, and only calls the C library function in the event that the result is NaN.

**Comment by jim-wilson** [comment]
The C library function is only called if we need errno set.  If you compile with -O -fno-math-errno you only get the fsqrt.s instruction.  -fno-math-errno assumes that you will use fenv.h functions instead of errno to check for errors.

rohan:2009$ cat tmp.c
#include <math.h>

float
sub (float a)
{
  return sqrtf (a);
}
rohan:2010$ riscv64-unknown-elf-gcc -O -S tmp.c -fno-math-errno
rohan:2011$ cat tmp.s
	.file	"tmp.c"
	.option nopic
	.text
	.align	1
	.globl	sub
	.type	sub, @function
sub:
	fsqrt.s	fa0,fa0
	ret
	.size	sub, .-sub
	.ident	"GCC: (GNU) 8.2.0"
rohan:2012$ 

Because newlib still requires that sqrt set errno, the library function can't be implemented with just a fsqrt.s instruction.  But we can replace the soft-float sqrt routine with a fsqrt.s instruction for a hard float target, and leave the rest of the implementation that checks for errors there.  Other targets do this.  See for instance newlib-cygwin/newlib/libm/machine/arm/ef_sqrt.c.  If we are doing this, we should probably do the full set of operations that can be easily open coded on RISC-V, and not just sqrt.

**Comment by jim-wilson** [comment]
Kito added the missing RISC-V math library hooks, and we are in the process of updating riscv-gnu-toolchain to a new version of newlib that contains these hooks, so I consider this fixed.
